<style type="text/css">
    .btnRow{border-bottom: 1px dashed #fff;}
    .btnRow:hover{border-bottom: none;margin-bottom: 1px;}
</style>
<div id="tab-pages">
    <div class="tab-page active">
        <div id="request">
            <div class="container">
                <div class="big-title blue">
                    Закажите услуги на свадьбу или праздник
                </div>
                <div class="min-title">Вам ответят в течение 15 минут</div>
                <form action="/projects/add" id="request-form" method="post">
                    <input type="hidden" name="mode" value="1">
                    <div class="top-line">
                        <div class="top-input" id="req-title-important">
                            <input id="req-title" name="req-title" type="text" onblur="if(this.value==''){this.value='Краткий заголовок заявки *';}" onfocus="if(this.value=='Краткий заголовок заявки *'){this.value='';}" value="Краткий заголовок заявки *">
                        </div>
                        <div class="top-input date">
                            <div class="calendar-ico"></div>
                            <input id="req-date-since" name="req-date-since" type="text" onblur="if(this.value==''){this.value='Дата начала';}" onfocus="if(this.value=='Дата начала'){this.value='';}" value="Дата начала" readonly="readonly">
                        </div>
                        <div class="top-input date">
                            <div class="calendar-ico"></div>
                            <input id="req-date-to" name="req-date-to" type="text" onblur="if(this.value==''){this.value='Дата завершения';}" onfocus="if(this.value=='Дата завершения'){this.value='';}" value="Дата завершения" readonly="readonly">
                        </div>
                    </div>
                    <div class="top-line">
                        <div class="top-area" id="req-text-important">
                            <textarea name="req-text" id="req-text" onblur="if(this.value==''){this.value='Максимально подробное описание заявки *';}" onfocus="if(this.value=='Максимально подробное описание заявки *'){this.value='';}">Максимально подробное описание заявки *</textarea>
                        </div>
                        <div class="top-area min contacts">
                            <div class="top-input">
                                <input id="req-title" name="req-phone" type="text" onblur="if(this.value==''){this.value='Телефон';}" onfocus="if(this.value=='Телефон'){this.value='';}" value="Телефон">
                            </div>
                            <div class="top-input">
                                <input id="req-title" name="req-mail" type="text" onblur="if(this.value==''){this.value='E-mail';}" onfocus="if(this.value=='E-mail'){this.value='';}" value="E-mail">
                            </div>
                            <div class="top-input">
                                <input id="req-budget" name="req-budget" type="text" onblur="if(this.value==''){this.value='Примерный бюджет';}" onfocus="if(this.value=='Примерный бюджет'){this.value='';}" value="Примерный бюджет">
                            </div>
                        </div>
                        <div class="top-check">
                            <div class="top-line">
                                <div class="chb radio">
                                    <div class="check"></div>
                                </div>
                                <label>Видно только специалистам</label>
                            </div>
                            <div class="top-line" style="margin-bottom: 23px;">
                                <div class="chb radio active">
                                    <div class="check"></div>
                                </div>
                                <label>Платное объявление всем<br>
                                    <span style="position:absolute; display:block; font-size: 11px;opacity:1;line-height: 12px; white-space: nowrap; top: 18px;">Без регистрации</span>
                                </label>
                            </div>
                            <div class="top-line">
                                <div class="chb radio">
                                    <div class="check"></div>
                                </div>
                                <label>Видно без контактов</label>

                            </div>
                            <input type="hidden" id="req-visiblilty" name="req-visiblilty">
                            <a href="#" class="reg">Регистрация на сайте</a>
                        </div>
                    </div>
                    <div class="top-services-wrap">
                        <div class="top-services" data-services="">
                            <?foreach($this->catalog_index as $item){?>
                            <div class="top-service" data-id="<?=$item->url?>" data-cat-id="<?=$item->id?>">
                                <span><?=$item->name?></span>
                                <div class="remove"></div>
                            </div>
                            <?}?>

                            <a href="#" class="add-service">Добавить / удалить услугу</a>
                        </div>
                        <input type="hidden" id="service-arr" name="service-arr">
                    </div>

                    <button type="submit" class="green-button">Отправить заявку</button>
                </form>

            </div>
        </div>
    </div>

    <div class="tab-page">
        <div class="big-title blue">рассчитайте бюджет мероприятия</div>
        <!-- <div class="min-title"><a href="#" class="full-calculator">Полная версия калькулятора</a><a href="#" class="express-calculator">Экспресс-калькулятор</a></div> -->
        <div class="add-service-ico">
            <div class="add-service-ico-title">Добавить / удалить услугу</div>
        </div>
    <div class="container">
    <div class="calc-services">
        <?foreach($this->catalog_index as $item){?>
        <div class="calc-service" data-id="<?=$item->url?>" data-cat-id="<?=$item->id?>">
            <a href="#" class="cat-item">
                <div class="cat-img">
                    <div class="cat-icon" style="background:url(/public/upload/projects_info/<?=$item->image?>) no-repeat 50% 50%; background-size: cover;"></div>
                </div>
                <span><?=htmlspecialchars($item->name)?></span>
            </a>
            <div class="price-slider-wrap">
                <div class="price-slider-chb">
                    <div class="chb active" data-min="1" data-max="1000">
                        <div class="check"></div>
                    </div>
                    <label>Стоимость в час</label>
                </div>
                <div class="price-slider-chb">
                    <div class="chb" data-min="1" data-max="5000">
                        <div class="check"></div>
                    </div>
                    <label>Стоимость за мероприятие / услугу</label>
                </div>

                <div class="price-slider-line" data-minprice="1" data-maxprice="1000">
                    <div class="price-slider-fill"></div>
                    <div class="price-slide left">
                        <span>1</span>
                    </div>
                    <div class="price-slide right">
                        <span>1000</span>
                    </div>
                </div>
            </div>
            <div class="calc-count">
                <div class="calc-count-title">Найдено исполнителей</div>
                <a href="/freelancers/<?=$item->url?>?price_start=1&amp;price_end=1000&amp;hour=1"><?=$this->serviceUserCount[$item->id]?></a>
            </div>
        </div>
        <?}?>
    </div>


            <div id="add-service-block">
                <a href="#" class="add-service"><span>Добавить / удалить услугу</span></a>
                <a href="#" style="border-bottom: none;line-height: 77px;margin-bottom: 0;margin-left: 10px;"><span id="btnlistFrilance" class="btnRow" style="color:white;">Список фрилансеров</span></a>
            </div>
            <div id="budget-block">
                <div class="min-title">
                    Примерный бюджет вашего мероприятия
                    <!-- <a href="#">Сохранить бюджет</a> -->
                </div>
                <div id="budget-price">1501</div>
                <div class="price-slider-line" data-minprice="2" data-maxprice="3000">
                    <div class="price-slider-fill" style="width: 169.225483655771px;"></div>
                    <div class="price-slide right" style="left: 169.225483655771px;"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-page">
        <div id="actions">
            <div id="image-slider">
                <div id="image-line">
                <?foreach($this->offers as $item){?>
                    <div class="image-item">
                        <img src="/public/upload/blur/<?=$item['image']?>" alt="">
                    </div>
                <?}?>
                </div>
            </div>
            <div id="text-slider">


            <?  $right='';
            foreach($this->offers as $item){?>
                <div class="text-item <?=$right?>">
                    <div class="biggest-text"><?=$item['caption']?></div>
                    <div class="text-slider-title"><?=$item['title']?></div>
                    <div class="text-slider-info"><?=$item['annotation']?></div>
                    <a href="#" class="green-button">Узнать больше</a>
                </div>
            <?
            $right='right';
            }?>


            </div>
            <div id="action-nav">
            <?
            $active = 'active';
            foreach($this->offers as $item){?>
                <div class="dot <?=$active?>"></div>
            <?
            $active='';
            }?>
            </div>
        </div>
    </div>
</div>

<div id="tab-menu">
    <div class="container">
        <a href="#" class="menu-item active"><span>Оставить заявку</span></a>
        <a href="#" class="menu-item"><span>Калькулятор услуг</span></a>
        <a href="#" class="menu-item"><span>Акции и спецпредложения</span></a>
    </div>
</div>







