</div>
<div id="performers">
   <div class="container">

      <?
      if(!empty($this->serviceUser))
         foreach($this->serviceUser as $key => $item){
            if(@isset($this->user[$key]['id'])){
               ?>
               ﻿
               <div class="performer-block">
                  <!--             <div class="performer-date-info-block">
                      <div class="performer-date-info">Последний раз был на сайте: 13-02-2015</div>
                      <div class="performer-date-info">Зарегистрирован: 235 дней назад</div>
                  </div> -->
                  <div class="performer-first">
                     <div class="performer">
                        <div class="photo-block" style="background: url(/public/upload/big/<?= $this->user[$key]['avatar'] ?>) 50% 50%; background-size: cover"></div>
                        <div class="performer-wrap">
                           <div class="performer-name"><?= $this->user[$key]['firstname'] . ' ' . $this->user[$key]['lastname'] ?></div>
                           <div class="performer-status"><? \Bootstrap::statusDay($this->reserve[$this->user[$key]['id']]) ?></div>
                        </div>
                     </div>
                     <a href="#" class="performer-busy">
                        Посмотреть свободные / занятые дни
                        <input type="text" id="<?= $this->user[$key]['id'] ?>" data-busy="<? \Bootstrap::reserveDay($this->reserve[$this->user[$key]['id']]) ?>" readonly="readonly">
                     </a>
                     <div class="performer-contact">
                        <label>Телефон:</label><?= $this->user[$key]['phone'] ?>
                     </div>
                     <div class="performer-contact">
                        <label>E-mail:</label><a href="mailto:<?= $this->user[$key]['email'] ?>"><?= $this->user[$key]['email'] ?></a>
                     </div>
                     <div class="performer-contact">
                        <label>Skype:</label><a href="#"><?= $this->user[$key]['skype'] ?></a>
                     </div>
                  </div>
                  <div class="performer-second">
                     <div class="performer-contact">
                        <label>Опыт работы:</label><?= $this->user[$key]['experience'] ?>
                     </div>
                     <div class="performer-contact">
                        <label>Цена за час:</label><?= $item['price'] ?> руб.
                     </div>
                     <div class="performer-contact">
                        <label>Цена за проект:</label><?= $item['projprice'] ?> руб.
                     </div>
                     <div class="performer-contact">
                        <label>Рейтинг:</label>
                        <? \Bootstrap::rating($this->rating[$this->user[$key]['id']], $this->rating_count[$this->user[$key]['id']]) ?>
                        <!-- <div class="star active"></div><div class="star active"></div><div class="star"></div><div class="star"></div><div class="star"></div> -->
                     </div>
                     <div class="extra-services">
                        <div class="extra-services-title">
                           Дополнительные услуги:
                        </div>
                        <?

                        foreach($this->serviceUserData[$item['userid']] as $i => $data){
                           if(isset($this->articleServAll[$data->tagid]) && $data->tagid != $this->serviceItem->id){
                              ?>

                              <a href="#" class="extra-service" title="<?= $this->articleServAll[$data->tagid]['name'] ?>">
                                 <div class="cat-icon" style="background:url(/public/upload/big/<?= $this->articleServAll[$data->tagid]['image'] ?>) no-repeat 50% 50%; background-size: cover;"></div>
                              </a>

                           <? }
                        } ?>
                     </div>
                  </div>
                  <div class="performer-photos">
                     <?
                     $count = 0;
                     foreach($this->serviceUserData[$item['userid']] as $data){
                        if($data->typeserv == 'photos' && isset($data->file_img)){
                           ?>
                           <div class="photo-block <?= $count >= 5 ? 'disabled' : '' ?>" style="background: url(/public/upload/big/<?= $data->file_img ?>) 50% 50%; background-size: cover" big="/public/upload/blur/<?= $data->file_img ?>"></div>
                           <? $count++;
                        }
                     } ?>
                     <a class="morephoto" href="#"><span>ещё</span></a>
                  </div>
                  <div class="performer-about">
                     <div class="performer-about-title">О себе:</div>
                     <div class="performer-about-text">
                        <?= $this->user[$key]['info'] ?>
                     </div>
                     <div class="performer-line">
                        <a class="performer-comment" href="#" data-id="<?= $data->userid ?>">Отзывы: <?= $this->review[$item['userid']] ?></a>
                     </div>
                     <a href="#" class="lightblue-button reserve">Забронировать исполнителя</a>
                     <a href="/profile/<?= $data->userid ?>" class="lightblue-button">Профиль</a>
                  </div>
               </div>
            <? }
         } ?>


      <!--
              <a href="#" class="performers-link">показать еще ...</a>
      -->
   </div>
</div>