<div class="content-items statictics">
    <div class="content-items-scroll-layer">
        <div class="content-items-list">
            <a class="content-item all active" href="#">
            	<span>Общая статистика</span>
            </a>
            <a class="content-item all" href="#">
            	<span>Активность</span>
            </a>
            <a class="content-item all" href="#">
            	<span>Рейтинг популярности страниц</span>
            </a>
            <a class="content-item all" href="#">
            	<span>История поиска</span>
            </a>
        </div>
    </div>
    <div class="scroller-line"></div>
</div>