<div id="new">
    <div class="container">
        <div class="big-title blue">
            <?= $this->article['title'] ?>
        </div>
        <div id="new-text">
            <?= $this->article['text'] ?>
            <br style="clear:both;">
        </div>
    </div>
</div>

</div>

<div id="articles" data-articles-count="<?= $this->articles_count ?>">
    <div class="container">
        <div class="big-title">Статьи</div>
        <div id="news-items">
            <? foreach($this->articles as $article){
                $date = new DateTime($article->created_at);
                $data = $date->format('Y-m-d');
                ?>
                <a href="/allabout/<?= $article->id ?>" class="news-item">
                    <div class="public-date"><?= $data ?></div>
                    <div class="news-title"><?= $article->title ?></div>
                </a>
            <? } ?>
        </div>
        <a href="#" class="all-articles">Ещё статьи</a>
        <? if(\Bootstrap::checkUserPro() && \Bootstrap::userGetRole() == 0){ ?>
            <a href="#" class="allabout_add_articles">Добавить статью</a>
        <? } ?>
    </div>
</div>