
<form action="/freelancers/photo" method="post">
    <div id="performers-page">
        <div class="container">
            <div class="big-title blue" data-cat-id="<?=$this->serviceItem->id?>"><?=htmlspecialchars($this->serviceItem->name)?></div>
            <div id="service-top-block">
                <div class="price-slider-wrap">
                    <div class="price-slider-chb">
                        <div data-max="1000" data-min="1" class="chb active">
                            <div class="check"></div>
                        </div>
                        <label>Стоимость в час</label>
                    </div>
                    <div class="price-slider-chb">
                        <div data-max="5000" data-min="1" class="chb">
                            <div class="check"></div>
                        </div>
                        <label>Стоимость за мероприятие / услугу</label>
                    </div>
                    <div class="price-slider-line" data-minprice="1" data-maxprice="1000">
                        <div class="price-slider-fill"></div>
                        <div class="price-slide left"><span>1</span></div>
                        <div class="price-slide right"><span>1000</span></div>
                    </div>
                </div>
            </div>
<!--             <div class="top-input date">
    <div class="calendar-ico"></div>
    <input id="event-date" name="event-date" type="text" onblur="if(this.value==''){this.value='Укажите дату(ы) события';}" onfocus="if(this.value=='Укажите дату(ы) события'){this.value='';}" value="Укажите дату(ы) события" readonly="readonly">
</div>
<input type="submit" value="Найти"> -->
        </div>
    </div>
</form>

    <div id="performers-filter">
    <div class="container">
        <div id="filter-title">Найдено исполнителей:</div>
        <div id="filter-count"><?=$this->count==''?'0':$this->count?></div>
<!--         <div class="top-label">Сортировать по:</div>
    <a href="/freelancers/photo?&amp;sort=rating" class="filter-link"><span>популярности</span></a>
    <a href="/freelancers/photo?&amp;sort=price" class="filter-link"><span>цене</span></a>
    <a href="/freelancers/photo?&amp;sort=reviews" class="filter-link"><span>кол-во отзывов</span></a>
     -->    </div>
</div>
</div>





<div id="performers">
    <div class="container">

        <?foreach($this->serviceUser as $key => $item){
            if(@isset($this->user[$key]['id'])){
            ?>
﻿        <div class="performer-block">
<!--             <div class="performer-date-info-block">
    <div class="performer-date-info">Последний раз был на сайте: 13-02-2015</div>
    <div class="performer-date-info">Зарегистрирован: 235 дней назад</div>
</div> -->
            <div class="performer-first">
                <div class="performer">
                    <div class="photo-block" style="background: url(/public/upload/big/<?=$this->user[$key]['avatar']?>) 50% 50%; background-size: cover"></div>
                    <div class="performer-wrap">
                        <div class="performer-name"><?=$this->user[$key]['firstname'].' '.htmlspecialchars($this->user[$key]['lastname'])?></div>
                        <div class="performer-status"><?\Bootstrap::statusDay($this->reserve[$this->user[$key]['id']])?></div>
                    </div>
                </div>
                <a href="#" class="performer-busy">
                    Посмотреть свободные / занятые дни
                    <input type="text" id="<?=$this->user[$key]['id']?>" data-busy="<?\Bootstrap::reserveDay($this->reserve[$this->user[$key]['id']])?>" readonly="readonly">
                </a>
                <div class="performer-contact">
                    <label>Телефон:</label><?=$this->user[$key]['phone']?>
                </div>
                <div class="performer-contact">
                    <label>E-mail:</label><a href="mailto:<?=htmlspecialchars($this->user[$key]['email'])?>"><?=htmlspecialchars($this->user[$key]['email'])?></a>
                </div>
                <div class="performer-contact">
                    <label>Skype:</label><a href="#"><?=htmlspecialchars($this->user[$key]['skype'])?></a>
                </div>
            </div>
            <div class="performer-second">
                <div class="performer-contact">
                    <label>Опыт работы:</label><?=htmlspecialchars($this->user[$key]['experience'])?>
                </div>
                <div class="performer-contact"> 
                    <label>Цена за час:</label><?=htmlspecialchars($item['price'])?> руб.
                </div>
                <div class="performer-contact">
                    <label>Цена за проект:</label><?=htmlspecialchars($item['projprice'])?> руб.
                </div>
                <div class="performer-contact">
                    <label>Рейтинг:</label>
                    <?\Bootstrap::rating($this->rating[$this->user[$key]['id']], $this->rating_count[$this->user[$key]['id']])?>
                </div>
                <div class="extra-services">
                    <div class="extra-services-title">
                        Дополнительные услуги:
                    </div>
                 <? foreach($this->serviceUserData[$item['userid']] as $i => $data){
                    if(isset($this->articleServAll[$data->tagid]) && $data->tagid != $this->serviceItem->id){?>

                  <a href="#" class="extra-service" title="<?=$this->articleServAll[$data->tagid]['name']?>">
                      <div class="cat-icon" style="background:url(/public/upload/big/<?=$this->articleServAll[$data->tagid]['image']?>) no-repeat 50% 50%; background-size: cover;"></div>
                  </a>

                <?}}?>
                </div>
            </div>
            <div class="performer-photos">
            <? $count=0;
            foreach($this->serviceUserData[$item['userid']] as $data){
                if($data->typeserv == 'photos' && isset($data->file_img)){?>
    				<div class="photo-block <?=$count>=5?'disabled':''?>" style="background: url(/public/upload/big/<?=$data->file_img?>) 50% 50%; background-size: cover" big="/public/upload/blur/<?=$data->file_img?>"></div>
                    <? $count++;
                }
            }?>
	                <a class="morephoto" href="#"><span>ещё</span></a>
            </div>
            <div class="performer-about">
                <div class="performer-about-title">О себе:</div>
                <div class="performer-about-text">
                    <?=htmlspecialchars($this->user[$key]['info'])?>
                </div>
                <div class="performer-line">
                    <a class="performer-comment" href="#" data-id="<?=$data->userid?>">Отзывы:  <?=htmlspecialchars($this->review[$item['userid']])?></a>
                </div>
                <a href="#" class="lightblue-button reserve">Забронировать исполнителя</a>
                <a href="/profile/<?=$data->userid?>" class="lightblue-button">Профиль</a>
                <br>
                <br>
                <?if(isset(\App::session('user')->id)){?>
                    <a href="#" class="lightblue-button btnchat" data-id="<?=$data->userid?>">Чат</a>
                <?}?>
            </div>
        </div>
        <?}}?>




<!--
        <a href="#" class="performers-link">показать еще ...</a>
-->
    </div>
</div>