<div id="orders-block">
    <div class="container">
        <div class="big-title">
            Лента заказов
        </div>
        <div id="order-nav">
        </div>
        <div id="order-items">
            <div id="order-line">
                <? foreach($this->projects as $item){ ?>
                    <div class="order-item" data-id="<?= $item['id'] ?>">
                        <div class="order-date"><?= $item['created_at'] ?></div>
                        <div class="order-info"><?= $item['title'] ?></div>
                        <? if(Bootstrap::checkUserPro()){ ?>
                            <a href="mailto:<?= $item['email'] ?>" class="order-mail"><?= $item['email'] ?></a>
                            <div class="order-phone"><?= $item['phone'] ?></div>
                        <? } ?>
                    </div>
                <? } ?>
            </div>
        </div>
    </div>
</div>