	<div class="bm-page-header new">
	    <h1 class="user-name">
	        <?=$this->currentUser->firstname?>
	    </h1>
	    <div class="bm-changes-message">
	    	Изменения сохранены
	    </div>
	    <div class="bm-changes-block">
	        <div class="bm-changes-block-title">Были внесены изменения</div>
	        <div class="bm-buttons">
	            <button class="bm-button cancel" data-ctrl="Page" href="<?=HTML::url('/users')?>">
	            	Отменить
	            </button>
	            <button type="submit" class="bm-button send">Сохранить</button>
	        </div>
	    </div>
	</div>
	<div id="bm-tab-menu">
		<?$links = array (
			'params' => 'Параметры пользователя',
			// 'password' => 'Пароль'
			//'access' => 'Управление доступом'
		);
		$str = '';
		foreach ($links as $key => $value) {
			if($this->file == $key)
				$str = 'class="active"';?>
			<a href="<?=HTML::url('/users/edit/id/'.$this->currentUser->id.'/change/' . $key);?>" <?=$str?> data-ctrl="Page"><?=$value?></a>
		<?$str = '';
		}?>
	</div>

	<div id="bm-page-tabs">
	    <div class="bm-page-tab">
	    	<?=$this->renderFile('users/' . $this->file);?>
	    </div>
	</div>
