<style>
    .top_menu {
        position: relative;
        display: inline-block;
        top: 9px;
    }
</style>

<div class="bm-page-header">
    <h1>Пользователи</h1>
    <div class="bm-changes-message">Изменения сохранены</div>
    <div class="bm-changes-block">
        <div class="bm-changes-block-title">Были внесены изменения</div>
        <div class="bm-buttons">
            <button class="bm-button cancel" data-ctrl="Page" href="<?= HTML::url('/user') ?>">
                Отменить
            </button>
            <button type="submit" class="bm-button">Сохранить</button>

        </div>
    </div>
</div>
<div id="bm-systemactive">
    <div id="bm-top-menu">
        <div class="bm-circle-button del" data-ctrl="User" data-act="removeUsers"></div>

        <label>
            Mail
            <div class="bm-form-error" id="bm-type-error"></div>
        </label>
        <select name="mail" id="mail_select">
            <? foreach($this->mails as $mail){
                echo $mail->title; ?>
                <option value="<?= $mail->id ?>"><?= '#' . $mail->id . ' ' . $mail->title ?></option>
            <? } ?>
        </select>


        <label for="executor">Исполнители</label>
        <div class="bm-checkbox <?= $this->params['executor'] == 'true' ? 'active' : '' ?> top_menu" id="executor" data-ctrl="Checkbox" data-act="filtr" href="<?= HTML::url('/users/index') ?>">
            <div class="bm-checkbox-choice"></div>
        </div>

        <label for="customer">Заказчики</label>
        <div class="bm-checkbox <?= $this->params['customer'] == 'true' ? 'active' : '' ?> top_menu" id="customer" data-ctrl="Checkbox" data-act="filtr" href="<?= HTML::url('/users/index') ?>">
            <div class="bm-checkbox-choice"></div>
        </div>


        <div class="bm-create-button" data-ctrl="Users" data-act="send_mail" href="<?= HTML::url('/users/send_mail') ?>">
            Отправить
        </div>

    </div>


</div>
<div class="bm-page-table users">
    <div class="bm-page-row header">
        <div class="bm-page-cell checkbox">
            <div class="bm-cell-elem">
                <div class="bm-checkbox" data-ctrl="Checkbox" data-act="all">
                    <div class="bm-checkbox-choice"></div>
                </div>
            </div>
        </div>

        <div class="bm-page-cell name">
            <div class="bm-cell-elem"><a class="bm-sort-link" href="#">Имя</a></div>
        </div>
        <div class="bm-page-cell mail">
            <div class="bm-cell-elem"><a class="bm-sort-link" href="#">E-mail</a></div>
        </div>
        <!--         <div class="bm-page-cell activity">
            <div class="bm-cell-elem"><a class="bm-sort-link" href="#">Активен</a></div>
        </div> -->
        <div class="bm-page-cell create">
            <div class="bm-cell-elem"><a class="bm-sort-link" href="#">Создан</a></div>
        </div>
        <!--         <div class="bm-page-cell admin">
            <div class="bm-cell-elem"><a class="bm-sort-link" href="#">Admin</a></div>
        </div> -->
    </div>

    <? foreach($this->users as $user){ ?>
        <div class="bm-page-row systemuser" data-itemid="<?= $user->id ?>">
            <div class="bm-page-cell checkbox">
                <div class="bm-cell-elem">
                    <div class="bm-checkbox" data-ctrl="Checkbox" data-itemid="<?= $user->id ?>">
                        <div class="bm-checkbox-choice"></div>
                    </div>
                </div>
            </div>
            <div class="bm-page-cell name">
                <div class="bm-cell-elem">
                    <a href="<?= HTML::url('/users/edit/id/' . $user->id) ?>" data-ctrl="Page">
                        <?= $user->firstname ?>
                    </a>
                </div>
            </div>
            <div class="bm-page-cell mail">
                <div class="bm-cell-elem">
                    <a href="mailto:<?= $user->email; ?>"><?= $user->email; ?></a>
                </div>
            </div>

            <!-- 	        <div class="bm-page-cell activity">
    <div class="bm-cell-elem">
    	<? if($user->active)
                echo date_format($user->active, 'd/m/Y');
            else
                echo "-"; ?>
    </div>
</div> -->

            <div class="bm-page-cell create">
                <div class="bm-cell-elem">
                    <?= date_format($user->created_at, 'd/m/Y'); ?>
                </div>
            </div>

            <!-- 	        <div class="bm-page-cell admin">
    <div class="bm-cell-elem">
    	<? $str = 'off';
            if($user->role == 1)
                $str = 'on'; ?>
        <div class="bm-radio main <?= $str ?>" data-ctrl="Radio" data-act="doroot"   data-itemid="<?= $user->id ?>">
            <div class="bm-radio-off"></div>
            <div class="bm-radio-on"></div>
            <div class="bm-radio-switcher"></div>
        </div>
    </div>
</div> -->

        </div>
    <? } ?>
</div>