<script type="text/javascript">
    $(document).ready(function (){
        $('input, textarea, .redactor_editor').on('input', function (){
            $('.bm-changes-block').show();
        });

        $('.bm-button.send').click(function (){
            $('form#' + Controller.User.change.id).submit();
        });
        $(".js-example-basic-multiple").select2();

        $('.date-form').Zebra_DatePicker({
            'days': ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            'months': ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
            'lang_clear_date': 'Очистить дату',
            'show_icon': false,
            'offset': [-308, 260],
            header_captions: {
                'days': 'F Y',
                'months': 'Y',
                'years': 'Y1 - Y2'
            },
            header_navigation: ['', '']
        });

        $('.bm-input.date').click(function (){
            $('.bm-input.date input').show();
        });

        $('#name').keyup(function (){
            var result = Controller.Articles.translit($(this).val());
            $('#bm-page-url').attr({'value': result});
        });

    });
</script>
<br>
<form action="<?= HTML::url('/users/save/id/' . $this->currentUser->id) ?>" method="POST" id="params">
    <div class="bm-page-content-editor">
        <div class="bm-page-content-editor-top">

            <label>
                Имя пользователя
                <div class="bm-form-error" style="position:relative; float:right;" id="error-name"></div>
            </label>
            <div class="bm-input fullwidth">
                <input type="text" id="firstname" name="firstname" value="<?= $this->currentUser->firstname ?>">
            </div>

            <label>
                Фамилия
                <div class="bm-form-error" style="position:relative; float:right;" id="error-name"></div>
            </label>
            <div class="bm-input fullwidth">
                <input type="text" id="lastname" name="lastname" value="<?= $this->currentUser->lastname ?>">
            </div>

            <label>
                Email пользователя
                <div class="bm-form-error" style="position:relative; float:right;" id="error-email"></div>
            </label>
            <div class="bm-input fullwidth">
                <input type="text" id="email" name="email" value="<?= $this->currentUser->email ?>">
            </div>

            <div class="bm-page-editor-left">
                <label>Дата завершения Pro</label>
                <div class="bm-input date">
                    <input type="text" name="date_end_pro" class="date-form" readonly="readonly" style="color:black;" value="<?= $this->currentUser->date_end_pro ?>">
                </div>
            </div>


            <div class="bm-page-editor-right">
                <label style="margin-bottom: 0;">Подписать на новости</label>
                <? HTML::radioUsers($this->currentUser, 'newsletter') ?>
            </div>
            <br><br><br><br><br>

            <div class="bm-page-editor-left">
                <label>Информация о <?= $this->currentUser->firstname ?></label>
                <div class="bm-textarea">
                    <textarea name="info" id="info"><?= $this->currentUser->info ?></textarea>
                </div>
            </div>

            <div class="bm-page-editor-right">
                <label>Аватарка</label>
                <div>
                    <div class="bm-dragndrop" <? if(isset($this->currentUser->avatar)){ ?> style="background:#ddd url(/public/upload/admin/<?= $this->currentUser->avatar ?>) 50% 50%; background-size:cover"<? } ?>>
                        <div class="bm-uploaded" id="image-field-image"></div>
                    </div>
                    <a data-ctrl="Image" data-act="remove" data-id="<?= $this->currentUser->id ?>" data-key="avatar" href="/admin/users/removeimage">Удалить</a>
                </div>
            </div>

        </div>
    </div>
    <input type="submit" style="visibility:hidden;">
</form>


<!-- +portfolio -->