<style>
    form *::-webkit-input-placeholder {
        color: #fff;
        font-size: 14px;
        padding: 0;
    }
</style>

<div id="performer-page">
    <div class="container">
        <div id="user-photo" style="background: url('/public/upload/big/<?= $this->user->avatar ?>') 50% 50%; background-size: cover;">
            <a href="#" class="change avatar"><span>Изменить фото</span></a>

            <form action="/executor/upload_avatar" method="post" id="upload-preview" enctype="multipart/form-data" target="executor_uplaod_avatar">
                <input type="file" name="userfiles" id="avatar-upload">
                <input type="hidden" name="type" value="avatar">
            </form>
            <iframe name="executor_uplaod_avatar" id="executor_uplaod_avatar" src="#" style="display:none"></iframe>
        </div>

        <script type="text/javascript">
            $("#avatar-upload").submit(function (){
                return false;
            });
            $("#avatar-upload").on("change", function (){
                $("#upload-preview").submit();
            });
        </script>

        <form action="/executor/change_profile" method="post" id="performer-data" class="preformer-name">
            <div class="big-title blue">
                <span>
                    <span class="user-name"><?= $this->user->firstname ?></span>
                    <div class="change-name-block">
                        <div class="top-input name">
                            <input id="firstname" name="firstname" type="text" placeholder="Введите имя" value="">
                        </div>
                        <button class="green-button">Изменить</button>
                        <button class="green-button">Отменить</button>
                    </div>
                    <a href="#" class="change name"><span>Редактировать имя</span></a>
                </span>
            </div>
        </form>

        <form action="/executor/change_pswd" method="post" id="performer-data" class="performer-password">
            <div class="change-password">
                <div class="change-password-block">
                    <div class="top-input">
                        <input id="new-pass" name="new-password" type="text" placeholder="Введите пароль" value="">
                    </div>
                    <div class="top-input">
                        <input id="repeat-pass" name="repeat-password" type="text" placeholder="Повторите пароль" value="">
                    </div>
                    <button type="submit" class="green-button">Изменить</button>
                    <button class="green-button">Отменить</button>
                </div>
                <a class="change-pass" href="#"><span>Изменить пароль</span></a>
            </div>
        </form>

        <form action="/executor/change_profile" method="post" id="performer-data" class="executor-profile">
            <div class="performer-form">
                <div class="performer-top">
                    <div class="top-line">
                        <div class="top-input">
                            <input id="performer-phone" name="phone" type="text" placeholder="Телефон" value="<?= $this->user->phone ?>">
                        </div>
                        <div class="top-input">
                            <input id="performer-exp" name="experience" type="text" placeholder="Опыт работы (полных лет)" value="<?= $this->user->experience ?>">
                        </div>
                    </div>
                    <div class="top-line">
                        <div class="top-input">
                            <input id="performer-mail" name="email" type="text" placeholder="Email" value="<?= $this->user->email ?>">
                        </div>
                        <div class="top-input">
                            <input id="performer-skype" name="skype" type="text" placeholder="Skype" value="<?= $this->user->skype ?>">
                        </div>
                    </div>
                </div>
                <div class="performer-top">
                    <div class="top-area">
                        <textarea name="info" id="req-text" placeholder="Дополнительная информация и контакты"><?= $this->user->info ?></textarea>
                    </div>

                    <div class="top-info">
                        <? if(!Bootstrap::checkUserPro()){ ?>
                            <div class="top-label">Аккаунт:</div>
                            <div class="top-value">Стандарт</div>
                            <a href="#" class="top-link-change"><span style="opacity: .7">Купить PRO</span> В процессе доработки</a>
                        <? } ?>

                        <!--                        <div class="top-label">Статус:</div>-->
                        <!--                        <div class="top-value">-->
                        <!--                            <span class="user-status">Свободен</span>-->
                        <!--                            <div class="change-status-block">-->
                        <!--                                <div class="top-chb">-->
                        <!--                                    <div class="chb">-->
                        <!--                                        <div class="check"></div>-->
                        <!--                                    </div>-->
                        <!--                                    <label>Свободен</label>-->
                        <!--                                </div>-->
                        <!--                                <div class="top-chb">-->
                        <!--                                    <div class="chb">-->
                        <!--                                        <div class="check"></div>-->
                        <!--                                    </div>-->
                        <!--                                    <label>Занят</label>-->
                        <!--                                </div>-->
                        <!--                            </div>-->
                        <!--                        </div>-->
                        <!--                        <a href="#" class="top-link-change status">Изменить</a>-->
                    </div>

                </div>
            </div>
            <button type="submit" class="green-button">Сохранить изменения</button>
        </form>

        <form action="/executor/services_save" method="post" id="performer-data" class="executor-service">
            <a href="#" class="add-service performer-service">Добавить услугу</a>
            <div class="top-services">
                <? if(count($this->user->UserService))
                    foreach($this->user->UserService as $service){ ?>
                        <div class="top-performer-service">
                            <div class="top-service" data-id="photo" data-cat-id="<?= $this->services[$service->service_id]->id ?>">
                                <span> <?= $this->services[$service->service_id]->name ?> </span>
                                <div class="remove"></div>
                            </div>
                            <div class="top-input">
                                <input id="executor-h-<?= $this->services[$service->service_id]->id ?>" name="[<?= $this->services[$service->service_id]->id ?>]price_h" type="number" placeholder="Цена за час (рублей)" value="<?= $service['price_h'] ?>">
                            </div>
                            <div class="top-input">
                                <input id="executor-project-<?= $this->services[$service->service_id]->id ?>" name="[<?= $this->services[$service->service_id]->id ?>]price_project" type="text" placeholder="Цена за проект (рублей)" value=" <?= $service['price_project'] ?>">
                            </div>
                        </div>
                    <? } ?>
            </div>
            <button type="submit" class="green-button">Сохранить изменения</button>
        </form>

    </div>
    <div class="performer-portfolio-top">
        <div class="container">
            <div class="top-label portfolio">Фото:</div>
            <div class="performer-portfolio-items">
                <span id="executor-photos">
                    <? foreach($this->user->UserPhotos as $photo){ ?>
                        <div id="<?= $photo->id ?>" class="photo-block-wrap">
                            <div class="photo-del">
                                <div class="photo-del-button"></div>
                            </div>
                            <a href="#" class="photo-block" style="background: url(/public/upload/big/<?= $photo->image ?>) 50% 50%; background-size: cover"
                               big="/public/upload/blur/<?= $photo->image ?>"></a>
                        </div>
                    <? } ?>
                </span>

                <a class="addfile photo" href="#"></a>

                <form action="/executor/photo_upload" enctype="multipart/form-data" id="upload-portfolio-form" method="post" target="upload_photos">
                    <input id="photo-upload" type="file" multiple="multiple" name="userfiles[]" accept="image">
                    <input type="hidden" name="type" value="photos">
                </form>
                <iframe name="upload_photos" id="upload_photos" src="#" style="display:none"></iframe>

            </div>
        </div>
    </div>
    <div class="performer-portfolio-top">
        <div class="container">
            <div class="top-label portfolio">Видео:</div>
            <div class="performer-portfolio-items">
                <span id="executor-video">
                    <? foreach($this->user->userVideo as $video){ ?>
                        <div id="<?= $video->id ?>" class="portfolio-block-wrap video-item">
                            <div class="portfolio-del">
                                <div class="portfolio-del-button"></div>
                            </div>
                            <a href="#" class="portfolio-block" style="background: url(/public/upload/big/<?= $video->image ?>) 50% 50%; background-size: cover" big="" video_link='<?= $video->video_code ?>'></a>
                        </div>
                    <? } ?>
                </span>
                <a class="addfile video" href="#"></a>
            </div>
        </div>
    </div>
    <div class="performer-portfolio-top">
        <div class="container">
            <div class="top-label portfolio">Презентации:</div>
            <div class="performer-portfolio-items">
                <span id="executor-present">
                    <? foreach($this->user->userPresentations as $presentation){ ?>
                        <div id="<?= $presentation->id ?>" class="portfolio-block-wrap present-item">
                            <div class="portfolio-del">
                                <div class="portfolio-del-button"></div>
                            </div>
                            <a href="/public/media/files/<?= $presentation->document ?>" target="_blank" class="portfolio-block" style="background: url(/public/upload/big/<?= $presentation->image ?>) 50% 50%; background-size: cover" big=""></a>
                        </div>
                    <? } ?>
                </span>
                <a class="addfile present" href="#"></a>
            </div>
        </div>
    </div>
</div>

</div>


<div id="performer-orders-block">
    <div class="container">
        <div id="performer-calendar">
            <input type="hidden" id="performer-busyday" data-busy="<?= empty($this->calendarStr) ? 0 : $this->calendarStr ?>" readonly="readonly">
        </div>

        <div id="performer-orders">
            <div class="big-title">Ваши заказы</div>
            <? foreach($this->projects as $project){
                $project = $project->project;
                ?>
                <div class="order-item" data-id="<?= $project->id ?>">
                    <div class="order-date"><?= $project->created_at ?></div>
                    <div class="order-info"><?= $project->title ?></div>
                    <a href="mailto:<?= $project->email ?>" class="order-mail"><?= $project->email ?></a>
                    <div class="order-phone"><?= $project->phone ?></div>
                </div>
            <? } ?>
        </div>
    </div>
</div>


<iframe name="upload_present" id="upload_present" src="#" style="display:none"></iframe>