<style>
    form *::-webkit-input-placeholder {
        color: #fff;
        font-size: 14px;
        padding: 0;
    }
</style>
<div id="tab-pages">
    <div class="tab-page active">
        <div id="user-page">
            <div class="container">
                <div id="user-photo" style="background: url(public/upload/big/<?= $this->user->avatar ?>) 50% 50%;background-size: cover;">
                    <a href="#" class="change avatar"><span>Изменить фото</span></a>
                    <form action="/customer/avatar_upload" method="post" id="upload-preview" enctype="multipart/form-data" target="upload_avatar">
                        <input type="file" name="userfiles" id="avatar-upload">
                        <input type="hidden" name="type" value="avatar">
                    </form>
                </div>
                <iframe name="upload_avatar" id="upload_avatar" src="#" style="display:none"></iframe>

                <script type="text/javascript">
                    $("#avatar-upload").submit(function (){
                        return false;
                    });

                    $("#avatar-upload").on("change", function (){
                        $("#upload-preview").submit();
                    });
                </script>

                <form action="/customer/change_profile" method="post" class="customer-user-name">
                    <div class="big-title blue">
                        <span>
                            <span class="user-name"><?= $this->user->firstname ?></span>
                            <div class="change-name-block">
                                <div class="top-input name">
                                    <input id="new-name" name="firstname" type="text" placeholder="Введите имя">
                                </div>
                                <button type="submit" class="green-button">Изменить</button>
                            </div>
                            <a href="#" class="change name"><span>Редактировать имя</span></a>
                        </span>
                    </div>
                </form>

                <form action="/customer/change_pswd" method="post" id="user-data" class="user-password customer-user-password">
                    <div class="change-password">
                        <div class="change-password-block">
                            <div class="top-input">
                                <input id="new-pass" name="password" type="text" placeholder="Введите пароль">
                            </div>
                            <div class="top-input">
                                <input id="repeat-pass" name="repeat-pass" type="text" placeholder="Повторите пароль">
                            </div>
                            <button type="submit" class="green-button">Изменить</button>
                        </div>
                        <a class="change-pass" href="#"><span>Изменить пароль</span></a>
                    </div>
                </form>

                <form action="/customer/change_profile" method="post" class="customer-user-profile">
                    <div class="top-input">
                        <input id="user-phone" name="phone" type="text" placeholder="Телефон" value="<?= $this->user->phone ?>">
                    </div>
                    <div class="top-input">
                        <input id="user-mail" name="email" type="text" placeholder="Email" value="<?= $this->user->email ?>">
                    </div>

                    <? $accaunt = Bootstrap::checkUserPro(); ?>
                    <div class="top-label">Аккаунт:</div>
                    <div class="top-value"><?= $accaunt ? 'Про' : 'Стандарт' ?></div>
                    <? if(!$accaunt){ ?>
                        <a href="#" class="top-link-change">Купить PRO</a>
                    <? } ?>
                    <br><br>
                    <button type="submit" class="green-button">Сохранить</button>
                </form>

            </div>
        </div>
    </div>

    <div class="tab-page">
        <div class="big-title blue">рассчитайте бюджет мероприятия</div>
        <div class="min-title"><span>экспресс калькулятор (до 3 услуг)</span><a href="#">Полная версия калькулятора</a></div>
        <div class="container">
            <div class="calc-services">
                <div class="calc-service" data-id="photo">
                    <a href="#" class="cat-item photo">
                        <div class="cat-img"></div>
                        <span>Фото</span>
                    </a>
                    <div class="price-slider-wrap">
                        <div class="price-slider-chb">
                            <div class="chb">
                                <div class="check"></div>
                            </div>
                            <label>Стоимость в час</label>
                        </div>
                        <div class="price-slider-chb">
                            <div class="chb">
                                <div class="check"></div>
                            </div>
                            <label>Стоимость за мероприятие / услугу</label>
                        </div>

                        <div class="price-slider-line" data-minprice="1000" data-maxprice="10000">
                            <div class="price-slider-fill"></div>
                            <div class="price-slide left"><span>1000</span></div>
                            <div class="price-slide right"><span>10000</span></div>
                        </div>
                    </div>
                    <div class="calc-count">
                        <div class="calc-count-title">Найдено исполнителей</div>
                        <a href="#">36</a>
                    </div>
                </div>
                <div class="calc-service" data-id="agency">
                    <a href="#" class="cat-item agency">
                        <div class="cat-img"></div>
                        <span>Свадебные агентства</span>
                    </a>
                    <div class="price-slider-wrap">
                        <div class="price-slider-chb">
                            <div class="chb">
                                <div class="check"></div>
                            </div>
                            <label>Стоимость в час</label>
                        </div>
                        <div class="price-slider-chb">
                            <div class="chb">
                                <div class="check"></div>
                            </div>
                            <label>Стоимость за мероприятие / услугу</label>
                        </div>

                        <div class="price-slider-line" data-minprice="1000" data-maxprice="15000">
                            <div class="price-slider-fill"></div>
                            <div class="price-slide left"><span>1000</span></div>
                            <div class="price-slide right"><span>15000</span></div>
                        </div>
                    </div>
                    <div class="calc-count">
                        <div class="calc-count-title">Найдено исполнителей</div>
                        <a href="#">36</a>
                    </div>
                </div>
            </div>
            <div id="add-service-block">
                <a href="#" class="add-service"><span>Добавить услугу</span></a>
            </div>
            <div id="budget-block">
                <div class="min-title">
                    Примерный бюджет вашего мероприятия
                    <a href="#">Сохранить бюджет</a>
                </div>
                <div id="budget-price">13500</div>
                <div class="price-slider-line" data-minprice="2000" data-maxprice="25000">
                    <div class="price-slider-fill" style="width: 198.391304347826px;"></div>
                    <div class="price-slide right" style="left: 198.391304347826px;"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-page">
        <div id="request">
            <div class="container">
                <div class="big-title blue">
                    Закажите услуги на свадьбу или праздник
                </div>
                <div class="min-title">Вам ответят в течение 15 минут</div>
                <form action="/edit" id="request-form" method="post">
                    <div class="top-line">
                        <div class="top-input">
                            <input id="req-title" name="req-title" type="text" placeholder="Краткий заголовок заявки" value="">
                        </div>
                        <div class="top-input date">
                            <div class="calendar-ico"></div>
                            <input id="req-date-since" name="req-date-since" type="text" placeholder="Дата начала" value="" readonly="readonly">
                        </div>
                        <div class="top-input date">
                            <div class="calendar-ico"></div>
                            <input id="req-date-to" name="req-date-to" type="text" placeholder="Дата завершения" value="" readonly="readonly">
                        </div>
                    </div>
                    <div class="top-line">
                        <div class="top-area">
                            <textarea name="req-text" id="req-text" placeholder="Максимально подробное описание заявки"></textarea>
                        </div>
                        <div class="top-area min contacts">
                            <div class="top-input">
                                <input id="req-title" name="req-phone" type="text" placeholder="Телефон" value="">
                            </div>
                            <div class="top-input">
                                <input id="req-title" name="req-mail" type="text" placeholder="E-mail" value="">
                            </div>
                        </div>
                        <div class="top-check">
                            <div class="top-line">
                                <div class="chb">
                                    <div class="check"></div>
                                </div>
                                <label>Видно только специалистам</label>
                            </div>
                            <div class="top-line">
                                <div class="chb">
                                    <div class="check"></div>
                                </div>
                                <label>Видно всем (платно)</label>
                            </div>
                            <div class="top-line">
                                <div class="chb">
                                    <div class="check"></div>
                                </div>
                                <label>Скрыто, жду писем в личку</label>
                            </div>
                            <a href="#" class="reg">Регистрация на сайте</a>
                        </div>
                    </div>
                    <div class="top-services-wrap">
                        <div class="top-services">
                            <div class="top-service" data-id="photo">
                                <span>Фото</span>
                                <div class="remove"></div>
                            </div>
                            <div class="top-service" data-id="beauty">
                                <span>Мастера красоты</span>
                                <div class="remove"></div>
                            </div>
                            <a href="#" class="add-service">Добавить услугу</a>
                        </div>
                    </div>

                    <button type="submit" class="green-button">Отправить заявку</button>
                </form>

            </div>
        </div>
    </div>
</div>


</div>
<div class="container">
    <div id="user-page" class="big-title">
        Уведомления
    </div>
    <ul style="height: 170px;overflow: auto;">
        <? foreach($this->user->UserMessagesInfo as $item){ ?>
            <li>
                <p style="color: rgba(1, 1, 1, 0.44);font-size: 13px;">
                    <span><?= Date($item->created_at) ?></span> -
                    <span><?= $item->description ?></span>
                </p>
            </li>
        <? } ?>
    </ul>
</div>


<div class="container">
    <div id="performer-orders" style="width: 100%;">
        <div class="big-title">Ваши заказы</div>
        <?
        $this->projects = [];
        foreach($this->user->userProjects as $project){ ?>
            <span style="display: inline-block;position: relative;">
                <div class="customer_remove_project" data-id="<?= $project->id ?>" style="cursor:pointer;width: 14px;position: absolute;right: -10px">X</div>
                <div class="order-item" data-id="<?= $project->id ?>">
                    <div class="order-date"><?= $project->created_at ?></div>
                    <div class="order-info"><?= $project->title ?></div>
                    <a href="mailto:<?= $project->email ?>" class="order-mail"><?= $project->email ?></a>
                    <div class="order-phone"><?= $project->phone ?></div>
                </div>
            </span>
        <? } ?>
    </div>
</div>