<div class="container">
    <div class="big-title blue">
        <div id="user-photo" style="background: url(/public/upload/big/<?= $this->user->avatar ?>) 50% 50%; background-size: cover"></div>
        <span class="user-name"><?= $this->user->firstname ?></span>
    </div>
</div>
<div id="performer-profile">
    <div class="container">
        <? if(\Bootstrap::checkUserPro()){ ?>
            <div class="performer-line">
                <label>Номер телефона:</label>
                <div class="performer-data"><?= $this->user->phone ?></div>
            </div>
            <div class="performer-line">
                <label>E-mail:</label>
                <div class="performer-data"><?= $this->user->email ?></div>
            </div>
            <div class="performer-line">
                <label>Skype:</label>
                <div class="performer-data"><?= $this->user->skype ?></div>
            </div>
        <? } ?>
    </div>
</div>

</div>