<script type="text/javascript">
	$(document).ready(function() {
		$('input, textarea, .redactor_editor').on('input', function () {
			$('.bm-changes-block').show();
		});

		$('.bm-button.send').click(function() {
			$('form#' + Controller.User.changePassword.id).submit();
		});
	});
</script>
<br>
<form action="<?=HTML::url('/user/settings')?>" method="POST" id="password_form">
	<input type="hidden" name="id" value="<?=$this->currentUser->id?>">
	<div class="bm-page-content-editor">
	    <div class="bm-page-content-editor-top">
	        <label>
	        	Новый пароль
	        	<div class="bm-form-error" style="position:relative;float:right;" id="error-password"></div>
	        </label>
	        <div class="bm-input fullwidth">
	            <input type="password" id="password" name="password">
	        </div>

	        <label>
	        	Повторите пароль
	        	<div class="bm-form-error" style="position:relative;float:right;" id="error-passrepeat">asdfsadfsafd</div>
	        </label>
	        <div class="bm-input fullwidth">
	            <input type="password" id="passrepeat" name="passrepeat">
	        </div>
	    </div>
	</div>
	<input type="submit" style="visibility:hidden;">
</form>