</div>
<div id="performers">
    <div class="container" style="text-align: left">
        <? foreach($this->services as $service){ ?>
            <ul>
                <li><a target="_blank" href="/service/<?= $service->url ?>"><?= $service->name ?></a></li>
            </ul>
        <? } ?>

        <? foreach($this->news as $news){ ?>
            <ul>
                <li><a target="_blank" href="/news/<?= $news->url ?>"><?= $news->name ?></a></li>
            </ul>
        <? } ?>

        <? foreach($this->articles as $article){ ?>
            <ul>
                <li><a target="_blank" href="/allabout/<?= $article->id ?>"><?= $article->title ?></a></li>
            </ul>
        <? } ?>
    </div>
</div>